"""Type stubs for `annflat._native`."""

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

__version__: str

class AnnflatError(Exception): ...

class Hit:
    @property
    def id(self) -> str: ...
    @property
    def score(self) -> float: ...
    def __repr__(self) -> str: ...

class Index:
    def __init__(self, *, metric: str = "cosine") -> None: ...
    @property
    def metric(self) -> str: ...
    @property
    def dim(self) -> int | None: ...
    def add(self, id: str, vector: NDArray[np.float32]) -> None: ...
    def add_batch(self, ids: list[str], matrix: NDArray[np.float32]) -> None: ...
    def search(self, query: NDArray[np.float32], k: int) -> list[Hit]: ...
    def search_batch(
        self, queries: NDArray[np.float32], k: int, *, parallel: bool = False
    ) -> list[list[Hit]]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
