[package]
name = "annflat-py"
description = "PyO3 bindings for annflat-core."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"
publish = false

[lib]
name = "annflat_native"
crate-type = ["cdylib"]

[dependencies]
annflat-core = { path = "../annflat-core", version = "0.1.0" }
pyo3 = { version = "0.23", features = ["abi3-py310", "extension-module"] }
rustc-hash = { workspace = true }
numpy = "0.29"
ndarray = { workspace = true }
